# write a docker compose including service local django server, keycloak, postgres db

version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: oncall
      POSTGRES_USER: oncall
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  keycloak:
    image: jboss/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: oncall
      DB_USER: oncall
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
      # Use the line below to bind to IPv4 instead of IPv6
      #BINDINGS: -b
  server:
    build: .
    ports:
      - 8080:8080

    
