# Generated by Django 4.2.1 on 2023-05-28 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_user"),
        ("schedules", "0002_rotation_rotationschedule_rotation_schedules"),
    ]

    operations = [
        migrations.AddField(
            model_name="rotation",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rotation",
                to="users.team",
            ),
        ),
        migrations.AlterField(
            model_name="rotation",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
