# Generated by Django 4.2.1 on 2023-05-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0003_rotation_team_alter_rotation_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rotationschedule",
            name="end_date",
            field=models.DateField(null=True),
        ),
    ]
